{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-registry.fullname" . }}-webhook
  labels:
    {{- include "kube-registry.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    {{- include "kube-registry.selectorLabels" . | nindent 4 }}
    app: webhook
{{- end }}
