# webhook配置
# https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers
{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kube-registry.fullname" . }}-webhook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kube-registry.fullname" . }}-webhook-certs
webhooks:
- name: {{ include "kube-registry.fullname" . }}.{{ .Release.Namespace }}.svc
  # 哪些请求需要发送webhook？
  # 创建pods的请求
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1"]
  # webhook发到哪里去？
  # 我们自己部署的webhook server
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "kube-registry.fullname" . }}-webhook
      path: /mutate
      port: 443
{{- end }}
