{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-selfhost-repo.fullname" . }}-webhook
  labels:
    {{- include "k8s-selfhost-repo.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    {{- include "k8s-selfhost-repo.selectorLabels" . | nindent 4 }}
    app: webhook
{{- end }}
