{{- if .Values.zot.s3.secret.accessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-registry.fullname" . }}-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.zot.s3.secret.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.zot.s3.secret.secretAccessKey | quote }}
{{- end }}
