{{- if .Values.zot.s3.config.region }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-registry.fullname" . }}-config
data:
  config.json: |
    {
      "distSpecVersion": "1.0.1-dev",
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "dedupe": true,
        "storageDriver": {
          "name": "s3",
          "region": "{{ .Values.zot.s3.config.region }}",
          {{- if .Values.zot.s3.config.regionEndpoint }}
          "regionEndpoint": "{{ .Values.zot.s3.config.regionEndpoint }}",
          {{- end }}
          "bucket": "{{ .Values.zot.s3.config.bucket }}",
          "secure": true,
          "skipverify": false
        }
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "log": {
        "level": "debug"
      },
      "extensions": {
        "sync": {
          "enable": true,
          "registries": [
            {
              "urls": ["https://ghcr.io"],
              "onDemand": true,
              "tlsVerify": true,
              "content": [
                {
                  "prefix": "**",
                  "destination": "/ghcr"
                }
              ]
            },
            {
              "urls": ["https://docker.io/library"],
              "onDemand": true,
              "tlsVerify": true,
              "content": [
                {
                  "prefix": "**",
                  "destination": "/dockerhub"
                }
              ]
            },
            {
              "urls": ["https://quay.io"],
              "onDemand": true,
              "tlsVerify": true,
              "content": [
                {
                  "prefix": "**",
                  "destination": "/quay"
                }
              ]
            },
            {
              "urls": ["https://registry.k8s.io"],
              "onDemand": true,
              "tlsVerify": true,
              "content": [
                {
                  "prefix": "**",
                  "destination": "/k8s"
                }
              ]
            }
          ]
        }
      }
    }
{{- end }}
