apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-zot.fullname" . }}
  labels:
    {{- include "my-zot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zot.service.type }}
  ports:
    - port: {{ .Values.zot.service.port }}
      targetPort: 5000
      protocol: TCP
      name: zot
      {{- if and (eq .Values.zot.service.type "NodePort") .Values.zot.service.nodePort }}
      nodePort: {{ .Values.zot.service.nodePort }}
      {{- end }}
  selector:
    {{- include "my-zot.selectorLabels" . | nindent 4 }}
